##############################################################################
# Apt Repositories
##############################################################################

ros2_distro    : "crystal"
ros2_key_server: "http://repo.ros2.org/repos.key"
ros2_apt_uri   : "http://packages.ros.org/ros2/ubuntu"

##############################################################################
# Apt Packages
##############################################################################

# see https://index.ros.org/doc/ros2/Linux-Install-Debians/
installation_packages:
  - curl
  - gnupg2
  - lsb-release

development_packages:
  - build-essential
  - cppcheck
  - cmake
  - python3-argcomplete
  - python3-colcon-*
  - python3-vcstool
